### ISSUE TITLE
License broken and no new version available

### ISSUE THREAD

**Issue by c-93** [riscv-ovpsim/imperas-riscv-tests#24]
License is broken with no new version (branch) available.

Steps to Reproduce:
1. `git clone git@github.com:riscv-ovpsim/imperas-riscv-tests.git`

2. Then switch directory:
`cd imperas-riscv-tests/riscv-ovpsim/bin/Linux64`

3. And simlply execute the simulator
`riscvOVPsim.exe`

Error:
```
Fatal (PER_TMO) Product riscvOVPsim version 20221017.0 license expired on 15 Jan 2023.
Please download a new version, or if not available please contact info@imperas.com and provide this information
Info Exiting
```
(Currently its Jan 16, 2023 16:51 Berlin Time Zone)

Edit: Added the error message.

**Comment by c-93** [comment]
With Current Branch v20221017

**Comment by Imperas** [comment]
Thanks for letting us know. We will get a new version up ASAP.

**Comment by c-93** [comment]
Thanks :).

**Comment by riscv-ovpsim** [comment]
new version v20230116 now up and the default branch.

**Comment by Vinayakamk** [comment]
currently the license is still broken and no longer the website taking registration on that website.

can anyone help here

**Comment by rishikakushwah16** [comment]
Error :
Fatal (PER_TMO) Product riscvOVPsim version 20230724.0 license expired on 23 Oct 2023.
Please download a new version, or if not available please contact info@imperas.com and provide this information
Info Exiting

I have gotten the same error message.

**Comment by duncangraham-Imperas** [comment]
I am afraid the riscvOVPsimPlus product from Imperas is no longer able to be provided via the github or OVPworld sites due to export compliance. We are working to make it available through other sources and will post as soon as possible.

If you are a customer of Imperas it is still possible to access the latest riscvOVPsimPlus through the Imperas customer portals. If you are not a customer of Imperas and wish to discuss, please contact us.
